name: Setup Build Variant Composite Action
description: Variant build actions for Meshtastic Platform IO steps

inputs:
  git-ref:
    description: The git ref (tag/branch) of the meshtastic firmware to checkout
    required: true
    default: "master"
  arch:
    description: Processor arch name
    required: true
    default: "esp32"
  board:
    description: The board to build for
    required: true

outputs:
  version:
    description: The version string of the build

runs:
  using: docker
  image: docker://ghcr.io/vidplace7/build-meshtastic:main
  args:
    - ${{ inputs.git-ref }}
    - --arch
    - ${{ inputs.arch }}
    - --board
    - ${{ inputs.board }}
