name: Setup Build Variant Composite Action
description: Variant build actions for Meshtastic Platform IO steps

inputs:
  git-ref:
    description: The git ref (tag/branch) of the meshtastic firmware to checkout
    required: true
    default: "master"
  arch:
    description: Processor arch name
    required: true
    default: "esp32"
  board:
    description: The board to build for
    required: true
  build-script-path:
    description: Path to the build script
    required: true
  remove-debug-flags:
    description: A space separated list of files to remove debug flags from
    required: false
    default: ""
  ota-firmware-source:
    description: The OTA firmware file to pull
    required: false
    default: ""
  ota-firmware-target:
    description: The target path to store the OTA firmware file
    required: false
    default: ""
  include-web-ui:
    description: Include the web UI in the build
    required: false
    default: "false"

outputs:
  version:
    description: The version string of the build

runs:
  using: docker
  image: docker://ghcr.io/vidplace7/build-meshtastic:main
  args:
    - ${{ inputs.git-ref }}
    - --arch
    - ${{ inputs.arch }}
    - --board
    - ${{ inputs.board }}
    - --build_script_path
    - ${{ inputs.build-script-path }}
